import { registerDriver } from "./base";
import { Pan115Driver } from "./115";
import { Open115Driver } from "./115_open";
import { Pan115ShareDriver } from "./115_share";
import { Pan123Driver } from "./123";
import { Pan123LinkDriver } from "./123_link";
import { Open123Driver } from "./123_open";
import { Pan123ShareDriver } from "./123_share";
import { Yun139Driver } from "./139";
import { Cloud189Driver } from "./189";
import { Cloud189TVDriver } from "./189_tv";
import { Cloud189PCDriver } from "./189pc";
import { AliasDriver } from "./alias";
import { AliDocDriver } from "./alidoc";
import { AlistV3Driver } from "./alist_v3";
import { AliyunDriveDriver } from "./aliyun";
import { AliyundriveOpenDriver } from "./aliyundrive_open";
import { AliyundriveShareDriver } from "./aliyundrive_share";
import { AutoIndexDriver } from "./autoindex";
import { AzureBlobDriver } from "./azure_blob";
import { BaiduNetdiskDriver } from "./baidu_netdisk";
import { BaiduPhotoDriver } from "./baidu_photo";
import { BunnyStorageDriver } from "./bunny_storage";
import { ChaoXingDriver } from "./chaoxing";
import { ChunkDriver } from "./chunk";
import { CloudreveDriver } from "./cloudreve";
import { CloudreveV4Driver } from "./cloudreve_v4";
import { CnbReleasesDriver } from "./cnb_releases";
import { CryptDriver } from "./crypt";
import { DegooDriver } from "./degoo";
import { DoubaoDriver } from "./doubao";
import { DoubaoNewDriver } from "./doubao_new";
import { DoubaoShareDriver } from "./doubao_share";
import { DropboxDriver } from "./dropbox";
import { FebBoxDriver } from "./febbox";
import { GitHubDriver } from "./github";
import { GitHubReleasesDriver } from "./github_releases";
import { GooglePhotoDriver } from "./google_photo";
import { GoogleDriveDriver } from "./googledrive";
import { HalalCloudDriver } from "./halalcloud";
import { HalalCloudOpenDriver } from "./halalcloud_open";
import { ILanZouDriver } from "./ilanzou";
import { IpfsApiDriver } from "./ipfs_api";
import { KodBoxDriver } from "./kodbox";
import { LanZouDriver } from "./lanzou";
import { LenovoNasShareDriver } from "./lenovonas_share";
import { MediaFireDriver } from "./mediafire";
import { MediaTrackDriver } from "./mediatrack";
import { MegaDriver } from "./mega";
import { MisskeyDriver } from "./misskey";
import { MopanDriver } from "./mopan";
import { NeteaseMusicDriver } from "./netease_music";
import { OneDriveDriver } from "./onedrive";
import { OnedriveAppDriver } from "./onedrive_app";
import { OnedriveSharelinkDriver } from "./onedrive_sharelink";
import { OpenListDriver } from "./openlist";
import { OpenListShareDriver } from "./openlist_share";
import { P115DriveDriver } from "./p115";
import { PikPakDriver } from "./pikpak";
import { PikPakShareDriver } from "./pikpak_share";
import { ProtonDriveDriver } from "./proton_drive";
import { QuarkDriveDriver } from "./quark";
import { QuarkOpenDriver } from "./quark_open";
import { QuarkUCDriver } from "./quark_uc";
import { QuarkUCTVDriver, UCTVDriver } from "./quark_uc_tv";
import { R2Driver } from "./r2";
import { S3Driver } from "./s3";
import { SeafileDriver } from "./seafile";
import { StrmDriver } from "./strm";
import { TeambitionDriver } from "./teambition";
import { TeldriveDriver } from "./teldrive";
import { TemplateDriver } from "./template";
import { TeraboxDriver } from "./terabox";
import { ThunderDriver } from "./thunder";
import { ThunderBrowserDriver } from "./thunder_browser";
import { ThunderXDriver } from "./thunderx";
import { UrlTreeDriver } from "./url_tree";
import { UssDriver } from "./uss";
import { VirtualDriver } from "./virtual";
import { WebDAVDriver } from "./webdav";
import { WeiyunDriver } from "./weiyun";
import { WopanDriver } from "./wopan";
import { WpsDriver } from "./wps";
import { YandexDiskDriver } from "./yandex_disk";

registerDriver("115", Pan115Driver);
registerDriver("115_open", Open115Driver);
registerDriver("115_share", Pan115ShareDriver);
registerDriver("123", Pan123Driver);
registerDriver("123_link", Pan123LinkDriver);
registerDriver("123_open", Open123Driver);
registerDriver("123_share", Pan123ShareDriver);
registerDriver("139", Yun139Driver);
registerDriver("189", Cloud189Driver);
registerDriver("189tv", Cloud189TVDriver);
registerDriver("189pc", Cloud189PCDriver);
registerDriver("alias", AliasDriver);
registerDriver("alidoc", AliDocDriver);
registerDriver("alist_v3", AlistV3Driver);
registerDriver("aliyun", AliyunDriveDriver);
registerDriver("aliyundrive_open", AliyundriveOpenDriver);
registerDriver("aliyundrive_share", AliyundriveShareDriver);
registerDriver("autoindex", AutoIndexDriver);
registerDriver("azure_blob", AzureBlobDriver);
registerDriver("baidu_netdisk", BaiduNetdiskDriver);
registerDriver("baidu_photo", BaiduPhotoDriver);
registerDriver("bunny_storage", BunnyStorageDriver);
registerDriver("chaoxing", ChaoXingDriver);
registerDriver("chunk", ChunkDriver);
registerDriver("cloudreve", CloudreveDriver);
registerDriver("cloudreve_v4", CloudreveV4Driver);
registerDriver("cnb_releases", CnbReleasesDriver);
registerDriver("crypt", CryptDriver);
registerDriver("degoo", DegooDriver);
registerDriver("doubao", DoubaoDriver);
registerDriver("doubao_new", DoubaoNewDriver);
registerDriver("doubao_share", DoubaoShareDriver);
registerDriver("dropbox", DropboxDriver);
registerDriver("febbox", FebBoxDriver);
registerDriver("github", GitHubDriver);
registerDriver("github_releases", GitHubReleasesDriver);
registerDriver("google_photo", GooglePhotoDriver);
registerDriver("googledrive", GoogleDriveDriver);
registerDriver("halalcloud", HalalCloudDriver);
registerDriver("halalcloud_open", HalalCloudOpenDriver);
registerDriver("ilanzou", ILanZouDriver);
registerDriver("ipfs_api", IpfsApiDriver);
registerDriver("kodbox", KodBoxDriver);
registerDriver("lanzou", LanZouDriver);
registerDriver("lenovonas_share", LenovoNasShareDriver);
registerDriver("mediafire", MediaFireDriver);
registerDriver("mediatrack", MediaTrackDriver);
registerDriver("mega", MegaDriver);
registerDriver("misskey", MisskeyDriver);
registerDriver("mopan", MopanDriver);
registerDriver("netease_music", NeteaseMusicDriver);
registerDriver("onedrive", OneDriveDriver);
registerDriver("onedrive_app", OnedriveAppDriver);
registerDriver("onedrive_sharelink", OnedriveSharelinkDriver);
registerDriver("openlist", OpenListDriver);
registerDriver("openlist_share", OpenListShareDriver);
registerDriver("p115", P115DriveDriver);
registerDriver("pikpak", PikPakDriver);
registerDriver("pikpak_share", PikPakShareDriver);
registerDriver("proton_drive", ProtonDriveDriver);
registerDriver("quark", QuarkDriveDriver);
registerDriver("quark_open", QuarkOpenDriver);
registerDriver("quark_uc", QuarkUCDriver);
registerDriver("uc_tv", QuarkUCTVDriver);
registerDriver("quark_uc_tv", UCTVDriver);
registerDriver("r2", R2Driver);
registerDriver("s3", S3Driver);
registerDriver("seafile", SeafileDriver);
registerDriver("strm", StrmDriver);
registerDriver("teambition", TeambitionDriver);
registerDriver("teldrive", TeldriveDriver);
registerDriver("template", TemplateDriver);
registerDriver("terabox", TeraboxDriver);
registerDriver("thunder", ThunderDriver);
registerDriver("thunder_browser", ThunderBrowserDriver);
registerDriver("thunderx", ThunderXDriver);
registerDriver("url_tree", UrlTreeDriver);
registerDriver("uss", UssDriver);
registerDriver("virtual", VirtualDriver);
registerDriver("webdav", WebDAVDriver);
registerDriver("weiyun", WeiyunDriver);
registerDriver("wopan", WopanDriver);
registerDriver("wps", WpsDriver);
registerDriver("yandex_disk", YandexDiskDriver);

export * from "./base";
